services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    command: ["python", "main.py"]
    restart: on-failure:5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: "host"

networks:
  mynetwork:
    driver: bridge
